name: "Release Build"

on:
  push:
    tags:
      - "v*.*.*"  # ${{ github.ref_name }} 必须是 v 开头的标签，例如 v0.0.1

jobs:
  publish:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: 'macos-latest' # for Arm based macs (M1 and above).
          #   args: '--target aarch64-apple-darwin'
          # - platform: 'macos-latest' # for Intel based macs.
          #   args: '--target x86_64-apple-darwin'
          - platform: "windows-latest"
            args: ""
          - platform: "ubuntu-22.04"
            args: ""
          - platform: "ubuntu-22.04-arm" # 24.04 是 arm 架构的 ubuntu 版本
            args: ""
          - platform: "ubuntu-latest"
            is_mobile: "android"
            args: "" # 移动端不用 args，后面单独处理

    runs-on: ${{ matrix.platform }}

    steps:

      - uses: actions/checkout@v4

      # ====================================================
      # 通用环境配置
      # ====================================================
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install frontend dependencies
        run: |
          corepack enable
          pnpm install --no-frozen-lockfile

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      # ====================================================
      # ubuntu 环境配置
      # ====================================================
      - name: install dependencies (ubuntu only)
        if: startsWith(matrix.platform, 'ubuntu') # This will match all Ubuntu platforms, including ubuntu-22.04, ubuntu-24.04, ubuntu-latest, etc.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      # ====================================================
      # 标准构建
      # ====================================================          
      # Desktop 自动 构建 (避开 tauri-action 的 build 命令)
      - name: Build Desktop & auto upload to release
        if: ${{ !matrix.is_mobile }}
        uses: tauri-apps/tauri-action@v0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          #tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          tagName: ${{ github.ref_name }}
          releaseName: "Release ${{ github.ref_name }}"
          generateReleaseNotes: true
          # releaseDraft: true
          # prerelease: false
          # mobile: ${{ matrix.mobile }}
          args: ${{ matrix.args }}

      # ====================================================
      # Android 构建
      # ====================================================
      - name: Setup Java (Android only)
        if: matrix.is_mobile
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          
      - name: Setup Android SDK
        if: matrix.is_mobile
        uses: android-actions/setup-android@v3

      - name: Restore Keystore
        if: matrix.is_mobile
        run: |
          printf '%s' "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d -i > release.jks
          ls -lh release.jks
          keytool -list -keystore release.jks -storepass "${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" -alias "${{ secrets.ANDROID_KEY_ALIAS }}"
          echo "--------------KEY PATH: ${{ github.workspace }}/release.jks "
          echo "--------------KEY ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }} "

      - name: Build Android
        if: matrix.is_mobile
        run: |
          pnpm tauri android init
          pnpm tauri android build --apk true
        env:
          TAURI_ANDROID_BUILD_TYPE: release
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/release.jks
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}     

      # 3. 对 APK 进行签名 (可选，用于直接分发)

      # - name: List Android Build Tools
      #   if: matrix.is_mobile
      #   run: ls $ANDROID_HOME/build-tools/

      # - name: Sign APK
      #   id: sign_apk
      #   if: matrix.is_mobile
      #   uses: r0adkll/sign-android-release@v1
      #   with:
      #     releaseDirectory: src-tauri/gen/android/app/build/outputs/apk/universal/release/
      #     signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      #     alias: ${{ secrets.ANDROID_KEY_ALIAS }}
      #     keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #     keyPassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      #   env:
      #     BUILD_TOOLS_VERSION: "35.0.0"

      - name: Upload Android APK to Release
        if: matrix.is_mobile
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          generate_release_notes: true
          files: |
            src-tauri/gen/android/app/build/outputs/apk/**/*.apk
          # ${{ steps.sign_apk.outputs.signedReleaseFile }}
          # src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk
          # src-tauri/gen/android/app/build/outputs/bundle/universalRelease/app-universal-release.aab
          # src-tauri/gen/android/app/build/outputs/**/release/*release.*
          # src-tauri/gen/android/app/build/outputs/apk/arm64/debug/app-arm64-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          

